# Generated by Django 4.1 on 2022-08-30 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nostaldja', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fads',
            new_name='Fad',
        ),
    ]
