# Generated by Django 4.1 on 2022-08-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decade',
            name='end_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='fads',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fads',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
