# Generated by Django 4.1 on 2022-08-30 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nosta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=100)),
                ('image_url', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(default='no descriptions', max_length=200)),
                ('decade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fads', to='nosta.decade')),
            ],
        ),
    ]
